########################################
# 应用名称：YouTube Block AD (Apple TV Optimized)
# 适用：Quantumult X（iPhone / iPad / Apple TV）
# 更新时间：2026
#
# 功能：
# ✓ 去播放前广告
# ✓ 去播放中广告（大多数情况）
# ✓ 去首页广告
# ✓ 去搜索广告
# ✓ 去 Shorts 广告
# ✓ 后台播放
# ✓ PIP
#
# 优化：
# ✓ 不修改 googlevideo 视频流
# ✓ 尽量保持 4K / HDR / AV1 播放速度
########################################

hostname = www.youtube.com,s.youtube.com,youtubei.googleapis.com

# ===============================
# YouTube JSON Rewrite
# ===============================

^https?:\/\/youtubei\.googleapis\.com\/youtubei\/v1\/(browse|next|player|search|reel\/reel_watch_sequence|guide|account\/get_setting|get_watch) url script-response-body https://raw.githubusercontent.com/Maasea/sgmodule/master/Script/Youtube/youtube.response.js

# ===============================
# 广告统计
# ===============================

^https?:\/\/(www|s)\.youtube\.com\/api\/stats\/ads url reject-200
^https?:\/\/(www|s)\.youtube\.com\/(pagead|ptracking) url reject-200
^https?:\/\/s\.youtube\.com\/api\/stats\/qoe\?adcontext url reject-200
